-- ============================================
-- MULTI-TENANCY MIGRATION FOR ZINGIQ
-- Adds organization-based data isolation
-- ============================================

-- ============================================
-- 1. CREATE ORGANIZATIONS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS "public"."organizations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "name" text NOT NULL,
    "slug" text UNIQUE NOT NULL,
    "settings" jsonb DEFAULT '{}',
    "plan" text DEFAULT 'free',
    "logo" jsonb
);

ALTER TABLE "public"."organizations" ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON "public"."organizations" TO "authenticated";
GRANT ALL ON "public"."organizations" TO "service_role";

-- ============================================
-- 2. ADD ORGANIZATION_ID TO SALES TABLE
-- ============================================

ALTER TABLE "public"."sales"
ADD COLUMN IF NOT EXISTS "organization_id" bigint REFERENCES "public"."organizations"(id);

-- ============================================
-- 3. CREATE HELPER FUNCTION
-- Get current user's organization_id
-- ============================================

CREATE OR REPLACE FUNCTION public.get_user_organization_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT organization_id FROM public.sales WHERE user_id = auth.uid() LIMIT 1
$$;

-- ============================================
-- 4. ADD ORGANIZATION_ID TO ALL DATA TABLES
-- ============================================

-- Companies
ALTER TABLE "public"."companies"
ADD COLUMN IF NOT EXISTS "organization_id" bigint REFERENCES "public"."organizations"(id);

-- Contacts
ALTER TABLE "public"."contacts"
ADD COLUMN IF NOT EXISTS "organization_id" bigint REFERENCES "public"."organizations"(id);

-- Contact Notes
ALTER TABLE "public"."contactNotes"
ADD COLUMN IF NOT EXISTS "organization_id" bigint REFERENCES "public"."organizations"(id);

-- Deals
ALTER TABLE "public"."deals"
ADD COLUMN IF NOT EXISTS "organization_id" bigint REFERENCES "public"."organizations"(id);

-- Deal Notes
ALTER TABLE "public"."dealNotes"
ADD COLUMN IF NOT EXISTS "organization_id" bigint REFERENCES "public"."organizations"(id);

-- Tags
ALTER TABLE "public"."tags"
ADD COLUMN IF NOT EXISTS "organization_id" bigint REFERENCES "public"."organizations"(id);

-- Tasks
ALTER TABLE "public"."tasks"
ADD COLUMN IF NOT EXISTS "organization_id" bigint REFERENCES "public"."organizations"(id);

-- ============================================
-- 5. CREATE AUTO-SET TRIGGER FUNCTION
-- Automatically sets organization_id on INSERT
-- ============================================

CREATE OR REPLACE FUNCTION public.set_organization_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Only set if not already provided
    IF NEW.organization_id IS NULL THEN
        NEW.organization_id := public.get_user_organization_id();
    END IF;
    RETURN NEW;
END;
$$;

-- ============================================
-- 6. CREATE TRIGGERS FOR EACH TABLE
-- ============================================

-- Companies trigger
DROP TRIGGER IF EXISTS companies_set_org_trigger ON "public"."companies";
CREATE TRIGGER companies_set_org_trigger
    BEFORE INSERT ON "public"."companies"
    FOR EACH ROW
    EXECUTE FUNCTION public.set_organization_id();

-- Contacts trigger
DROP TRIGGER IF EXISTS contacts_set_org_trigger ON "public"."contacts";
CREATE TRIGGER contacts_set_org_trigger
    BEFORE INSERT ON "public"."contacts"
    FOR EACH ROW
    EXECUTE FUNCTION public.set_organization_id();

-- Contact Notes trigger
DROP TRIGGER IF EXISTS contactnotes_set_org_trigger ON "public"."contactNotes";
CREATE TRIGGER contactnotes_set_org_trigger
    BEFORE INSERT ON "public"."contactNotes"
    FOR EACH ROW
    EXECUTE FUNCTION public.set_organization_id();

-- Deals trigger
DROP TRIGGER IF EXISTS deals_set_org_trigger ON "public"."deals";
CREATE TRIGGER deals_set_org_trigger
    BEFORE INSERT ON "public"."deals"
    FOR EACH ROW
    EXECUTE FUNCTION public.set_organization_id();

-- Deal Notes trigger
DROP TRIGGER IF EXISTS dealnotes_set_org_trigger ON "public"."dealNotes";
CREATE TRIGGER dealnotes_set_org_trigger
    BEFORE INSERT ON "public"."dealNotes"
    FOR EACH ROW
    EXECUTE FUNCTION public.set_organization_id();

-- Tags trigger
DROP TRIGGER IF EXISTS tags_set_org_trigger ON "public"."tags";
CREATE TRIGGER tags_set_org_trigger
    BEFORE INSERT ON "public"."tags"
    FOR EACH ROW
    EXECUTE FUNCTION public.set_organization_id();

-- Tasks trigger
DROP TRIGGER IF EXISTS tasks_set_org_trigger ON "public"."tasks";
CREATE TRIGGER tasks_set_org_trigger
    BEFORE INSERT ON "public"."tasks"
    FOR EACH ROW
    EXECUTE FUNCTION public.set_organization_id();

-- ============================================
-- 7. DROP EXISTING RLS POLICIES
-- ============================================

-- Organizations policies (new table, no existing policies)

-- Companies policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."companies";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."companies";
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON "public"."companies";
DROP POLICY IF EXISTS "Company Delete Policy" ON "public"."companies";

-- Contacts policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."contacts";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."contacts";
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON "public"."contacts";
DROP POLICY IF EXISTS "Contact Delete Policy" ON "public"."contacts";

-- Contact Notes policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."contactNotes";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."contactNotes";
DROP POLICY IF EXISTS "Contact Notes Delete Policy" ON "public"."contactNotes";
DROP POLICY IF EXISTS "Contact Notes Update policy" ON "public"."contactNotes";

-- Deals policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."deals";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."deals";
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON "public"."deals";
DROP POLICY IF EXISTS "Deals Delete Policy" ON "public"."deals";

-- Deal Notes policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."dealNotes";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."dealNotes";
DROP POLICY IF EXISTS "Deal Notes Delete Policy" ON "public"."dealNotes";
DROP POLICY IF EXISTS "Deal Notes Update Policy" ON "public"."dealNotes";

-- Sales policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."sales";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."sales";
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON "public"."sales";

-- Tags policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."tags";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."tags";
DROP POLICY IF EXISTS "Enable delete for authenticated users only" ON "public"."tags";
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON "public"."tags";
DROP POLICY IF EXISTS "tags_policy" ON "public"."tags";

-- Tasks policies
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."tasks";
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON "public"."tasks";
DROP POLICY IF EXISTS "Task Delete Policy" ON "public"."tasks";
DROP POLICY IF EXISTS "Task Update Policy" ON "public"."tasks";

-- ============================================
-- 8. CREATE NEW RLS POLICIES WITH ORG ISOLATION
-- ============================================

-- ORGANIZATIONS POLICIES
-- Users can only see their own organization
CREATE POLICY "org_select" ON "public"."organizations"
    FOR SELECT TO authenticated
    USING (id = public.get_user_organization_id());

CREATE POLICY "org_update" ON "public"."organizations"
    FOR UPDATE TO authenticated
    USING (id = public.get_user_organization_id())
    WITH CHECK (id = public.get_user_organization_id());

-- Service role can do anything (for signup flow)
CREATE POLICY "org_service_all" ON "public"."organizations"
    FOR ALL TO service_role
    USING (true)
    WITH CHECK (true);

-- SALES POLICIES
-- Users can only see sales in their organization
CREATE POLICY "sales_select" ON "public"."sales"
    FOR SELECT TO authenticated
    USING (organization_id = public.get_user_organization_id());

CREATE POLICY "sales_insert" ON "public"."sales"
    FOR INSERT TO authenticated
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "sales_update" ON "public"."sales"
    FOR UPDATE TO authenticated
    USING (organization_id = public.get_user_organization_id())
    WITH CHECK (organization_id = public.get_user_organization_id());

-- Service role can do anything (for signup flow)
CREATE POLICY "sales_service_all" ON "public"."sales"
    FOR ALL TO service_role
    USING (true)
    WITH CHECK (true);

-- COMPANIES POLICIES
CREATE POLICY "companies_select" ON "public"."companies"
    FOR SELECT TO authenticated
    USING (organization_id = public.get_user_organization_id());

CREATE POLICY "companies_insert" ON "public"."companies"
    FOR INSERT TO authenticated
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "companies_update" ON "public"."companies"
    FOR UPDATE TO authenticated
    USING (organization_id = public.get_user_organization_id())
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "companies_delete" ON "public"."companies"
    FOR DELETE TO authenticated
    USING (organization_id = public.get_user_organization_id());

-- CONTACTS POLICIES
CREATE POLICY "contacts_select" ON "public"."contacts"
    FOR SELECT TO authenticated
    USING (organization_id = public.get_user_organization_id());

CREATE POLICY "contacts_insert" ON "public"."contacts"
    FOR INSERT TO authenticated
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "contacts_update" ON "public"."contacts"
    FOR UPDATE TO authenticated
    USING (organization_id = public.get_user_organization_id())
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "contacts_delete" ON "public"."contacts"
    FOR DELETE TO authenticated
    USING (organization_id = public.get_user_organization_id());

-- CONTACT NOTES POLICIES
CREATE POLICY "contactnotes_select" ON "public"."contactNotes"
    FOR SELECT TO authenticated
    USING (organization_id = public.get_user_organization_id());

CREATE POLICY "contactnotes_insert" ON "public"."contactNotes"
    FOR INSERT TO authenticated
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "contactnotes_update" ON "public"."contactNotes"
    FOR UPDATE TO authenticated
    USING (organization_id = public.get_user_organization_id())
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "contactnotes_delete" ON "public"."contactNotes"
    FOR DELETE TO authenticated
    USING (organization_id = public.get_user_organization_id());

-- DEALS POLICIES
CREATE POLICY "deals_select" ON "public"."deals"
    FOR SELECT TO authenticated
    USING (organization_id = public.get_user_organization_id());

CREATE POLICY "deals_insert" ON "public"."deals"
    FOR INSERT TO authenticated
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "deals_update" ON "public"."deals"
    FOR UPDATE TO authenticated
    USING (organization_id = public.get_user_organization_id())
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "deals_delete" ON "public"."deals"
    FOR DELETE TO authenticated
    USING (organization_id = public.get_user_organization_id());

-- DEAL NOTES POLICIES
CREATE POLICY "dealnotes_select" ON "public"."dealNotes"
    FOR SELECT TO authenticated
    USING (organization_id = public.get_user_organization_id());

CREATE POLICY "dealnotes_insert" ON "public"."dealNotes"
    FOR INSERT TO authenticated
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "dealnotes_update" ON "public"."dealNotes"
    FOR UPDATE TO authenticated
    USING (organization_id = public.get_user_organization_id())
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "dealnotes_delete" ON "public"."dealNotes"
    FOR DELETE TO authenticated
    USING (organization_id = public.get_user_organization_id());

-- TAGS POLICIES
CREATE POLICY "tags_select" ON "public"."tags"
    FOR SELECT TO authenticated
    USING (organization_id = public.get_user_organization_id());

CREATE POLICY "tags_insert" ON "public"."tags"
    FOR INSERT TO authenticated
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "tags_update" ON "public"."tags"
    FOR UPDATE TO authenticated
    USING (organization_id = public.get_user_organization_id())
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "tags_delete" ON "public"."tags"
    FOR DELETE TO authenticated
    USING (organization_id = public.get_user_organization_id());

-- TASKS POLICIES
CREATE POLICY "tasks_select" ON "public"."tasks"
    FOR SELECT TO authenticated
    USING (organization_id = public.get_user_organization_id());

CREATE POLICY "tasks_insert" ON "public"."tasks"
    FOR INSERT TO authenticated
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "tasks_update" ON "public"."tasks"
    FOR UPDATE TO authenticated
    USING (organization_id = public.get_user_organization_id())
    WITH CHECK (organization_id = public.get_user_organization_id());

CREATE POLICY "tasks_delete" ON "public"."tasks"
    FOR DELETE TO authenticated
    USING (organization_id = public.get_user_organization_id());

-- ============================================
-- 9. UPDATE VIEWS TO INCLUDE ORG CONTEXT
-- ============================================

-- Drop and recreate companies_summary view
DROP VIEW IF EXISTS "public"."companies_summary";
CREATE VIEW "public"."companies_summary"
    WITH (security_invoker=on)
    AS
SELECT
    c.*,
    COUNT(DISTINCT d.id) AS nb_deals,
    COUNT(DISTINCT co.id) AS nb_contacts
FROM
    "public"."companies" c
LEFT JOIN
    "public"."deals" d ON c.id = d.company_id AND d.organization_id = c.organization_id
LEFT JOIN
    "public"."contacts" co ON c.id = co.company_id AND co.organization_id = c.organization_id
GROUP BY
    c.id;

-- Drop and recreate contacts_summary view
DROP VIEW IF EXISTS "public"."contacts_summary";
CREATE VIEW "public"."contacts_summary"
    WITH (security_invoker=on)
    AS
SELECT
    co.*,
    c.name AS company_name,
    COUNT(DISTINCT t.id) AS nb_tasks
FROM
    "public"."contacts" co
LEFT JOIN
    "public"."tasks" t ON co.id = t.contact_id AND t.organization_id = co.organization_id
LEFT JOIN
    "public"."companies" c ON co.company_id = c.id AND c.organization_id = co.organization_id
GROUP BY
    co.id, c.name;

-- ============================================
-- 10. CREATE INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS idx_companies_org ON "public"."companies"(organization_id);
CREATE INDEX IF NOT EXISTS idx_contacts_org ON "public"."contacts"(organization_id);
CREATE INDEX IF NOT EXISTS idx_contactnotes_org ON "public"."contactNotes"(organization_id);
CREATE INDEX IF NOT EXISTS idx_deals_org ON "public"."deals"(organization_id);
CREATE INDEX IF NOT EXISTS idx_dealnotes_org ON "public"."dealNotes"(organization_id);
CREATE INDEX IF NOT EXISTS idx_tags_org ON "public"."tags"(organization_id);
CREATE INDEX IF NOT EXISTS idx_tasks_org ON "public"."tasks"(organization_id);
CREATE INDEX IF NOT EXISTS idx_sales_org ON "public"."sales"(organization_id);

-- ============================================
-- MIGRATION COMPLETE
-- ============================================
